#ifndef error_list_hpp_
#define error_list_hpp_
#define INVALIDARGUMENTS "INVALID_ARGUMENTS"
#define DUPLICATEMISSIONID "DUPLICATE_MISSION_ID"
#define DUPLICATEDRIVERMISSION "DUPLICATE_DRIVER_MISSION"
#define MISSIONNOTFOUND "MISSION_NOT_FOUND"
#define INVALIDCOMMAND "INVALID_COMMAND"

#define INVALIDARGUMENTSCODE 101
#define DUPLICATEMISSIONIDCODE 102
#define DUPLICATEDRIVERMISSIONCODE 103
#define MISSIONNOTFOUNDCODE 104
#define INVALIDCOMMANDCODE 105
#define OK "OK"
#endif